In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
#loading of the data and selecting most relevant features, dropping columns that are lacking data
df = pd.read_csv("project_data.csv")
df2 = df.dropna()
y = df2['Total early-stage Entrepreneurial Activity (TEA)']

X = df2.drop(['economy','Total early-stage Entrepreneurial Activity (TEA)'], axis=1)

In [2]:
#spliting data, fitting it into Linear Regression 
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
coeff_df = pd.DataFrame(regressor.coef_, X.columns, columns=['Coefficient'])
#printing coefficients
print(coeff_df)


                                Coefficient
code                               0.002215
year                               0.057052
Perceived opportunities            0.026152
Perceived capabilities             0.014804
Fear of failure rate *             0.011519
Entrepreneurial intentions         0.183563
Established Business Ownership     0.279211
Female/Male TEA                    1.638814
High Job Creation Expectation      0.060891
Business Services Sector           0.016060


In [3]:

#making predictions, printing scores
y_pred = regressor.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 1.4528630501550506
Mean Squared Error: 3.4326069784211195
Root Mean Squared Error: 1.8527296020793536


In [4]:
#predicting using Support vector machine
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import svm
y = y.apply(np.int64)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
clf = svm.SVC()
clf.fit(X_train, y_train)
clf.predict(X_test)
y_pred=pd.DataFrame(y_pred)
y_pred = y_pred.apply(np.int64)
#confusion matrix - important when evaluating how far from the truth was the algorithm 
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[[0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 2 0 0 0 0]
 [0 0 0 0 2 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 2 1 0 4 0 0 0 0]
 [0 2 0 2 1 1 4 1 0 1 0 0 0 1]
 [0 0 0 1 2 4 4 1 0 0 1 0 0 0]
 [0 0 1 1 3 4 2 1 1 0 0 0 0 0]
 [0 0 0 1 5 2 2 3 0 0 0 0 0 0]
 [0 0 0 0 2 1 1 1 3 1 1 0 0 0]
 [0 0 1 1 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0]]
0.14942528735632185


In [5]:
#prediction using Gaussian NB
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()



X_train = pd.DataFrame(X_train)
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print(y_pred)
#confusion matrix - important when evaluating how far from the truth was the algorithm 
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[13  5  5  5  5  8  4 13  5  5  4 13  3  7  9  6 12 11  5 10  8  5  3  4
  5  5  5  4  7  3  7  5  5 13  6  9  5  9  5  5 10  5  7  5 13  4  6  5
  5  7  5  8  6  5  3  8 14  5  7  5  5  8 13  5 12  5  5  8  2  5 13  6
  9  7  3  5  6  5 10  4  8  8  4  9  5  5  5]
[[1 1 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 0 1 1 0 0 0 0 1 0 0]
 [0 1 1 7 2 0 0 0 0 0 0 0 0 0]
 [0 1 2 5 1 2 2 1 0 0 0 0 0 0]
 [0 0 2 8 1 1 1 0 0 0 0 1 0 0]
 [0 0 0 5 1 0 1 1 1 0 0 0 0 0]
 [0 0 0 3 0 2 1 1 1 0 0 0 0 0]
 [0 0 0 2 0 1 2 2 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 1 1 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0]]
0.1724137931034483
