In [42]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
#loading of the data and selecting most relevant features, dropping columns that are lacking data
df = pd.read_csv("project_data.csv")
df2 = df.dropna()
y = df2['Total early-stage Entrepreneurial Activity (TEA)']

X = df2.drop(['economy','Total early-stage Entrepreneurial Activity (TEA)'], axis=1)

In [43]:
#spliting data, fitting it into Linear Regression 
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
coeff_df = pd.DataFrame(regressor.coef_, X.columns, columns=['Coefficient'])
#printing coefficients
print(coeff_df)


                                Coefficient
code                               0.003123
year                               0.058145
Perceived opportunities            0.023357
Perceived capabilities            -0.000389
Fear of failure rate *             0.009191
Entrepreneurial intentions         0.177840
Established Business Ownership     0.256180
Female/Male TEA                    1.596360
High Job Creation Expectation      0.059668
Business Services Sector           0.011596


In [44]:

#making predictions, printing scores
y_pred = regressor.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 1.6107549350398933
Mean Squared Error: 3.98807284746978
Root Mean Squared Error: 1.997015985782232


In [50]:
#
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import svm
y = y.apply(np.int64)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
clf = svm.SVC()
clf.fit(X_train, y_train)
clf.predict(X_test)
y_pred=pd.DataFrame(y_pred)
y_pred = y_pred.apply(np.int64)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 2 2 2 0 1 0 0 0 0 0 0]
 [0 0 1 1 1 3 5 0 1 0 1 0 0 0 0]
 [0 0 1 2 1 3 1 1 0 0 0 0 0 0 0]
 [0 0 0 1 3 3 1 1 1 1 0 0 0 0 0]
 [0 0 0 1 0 3 2 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 2 2 2 1 0 0 0 0]
 [0 0 0 0 1 3 1 3 1 0 1 0 0 0 0]
 [0 0 1 0 0 1 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 2 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]]
0.13793103448275862


In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()



X_train = pd.DataFrame(X_train)
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print(y_pred)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[ 5  5  5  5  5  5  4  9  5  3  7  5  3  5  5  5  5  6 11 11  5  9  3  6
  3  6  5  2 11  7  5  5  5  7  6  5  9  3 12  5  6  5  6  7 10  7  5  3
  5  5  5  5  7  8  7  5 13  8  2  7  4  9  5  5  5  9  3  8 10  5  5 12
  5 13  5  5  7  5 13  5 13 15  4  8  2  5 11]
[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 1 1 1 0 1 0 0 0 0 0 0 0]
 [0 0 2 1 5 3 0 0 1 0 0 0 0 0 0]
 [0 1 1 1 8 0 2 0 0 0 0 0 0 0 0]
 [0 0 1 0 8 1 2 1 0 1 0 0 0 0 0]
 [0 0 0 0 6 1 2 2 1 0 0 0 0 0 0]
 [0 1 0 0 4 0 1 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 1 1 0 0 1 0 0]
 [0 0 0 0 2 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
0.21839080459770116
