In [8]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split

df = pd.read_csv("project_data.csv")
df2 = df.dropna()
y = df2['Total early-stage Entrepreneurial Activity (TEA)']

X = df2[['code', 'year', 'Perceived opportunities', 'Perceived capabilities', 'Fear of failure rate *', 'Entrepreneurial intentions', 'Established Business Ownership', 'Female/Male TEA', 'High Job Creation Expectation', 'Business Services Sector']]

In [9]:
print(y)

0      13.48
1      12.35
2       8.37
3       7.89
4       7.70
       ...  
440     4.63
441     4.59
442     3.90
443     7.13
444     5.36
Name: Total early-stage Entrepreneurial Activity (TEA), Length: 431, dtype: float64


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
coeff_df = pd.DataFrame(regressor.coef_, X.columns, columns=['Coefficient'])
print(coeff_df)


                                Coefficient
code                               0.002033
year                               0.063310
Perceived opportunities            0.029221
Perceived capabilities             0.007113
Fear of failure rate *             0.008730
Entrepreneurial intentions         0.180142
Established Business Ownership     0.303323
Female/Male TEA                    1.369277
High Job Creation Expectation      0.071033
Business Services Sector          -0.000656


In [11]:
y_pred = regressor.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 1.478187545333702
Mean Squared Error: 3.8713314461653927
Root Mean Squared Error: 1.9675699342502144


In [12]:
print (X_train)

     code  year  Perceived opportunities  Perceived capabilities  \
291    30  2009                    26.48                   58.06   
227     7  2012                    20.08                   23.50   
78     46  2018                    81.56                   38.42   
371    32  2005                    42.51                   44.49   
42    385  2019                    55.66                   71.19   
..    ...   ...                      ...                     ...   
126    32  2015                    40.26                   31.89   
241    49  2011                    35.17                   37.14   
352   420  2006                    26.73                   37.98   
113   371  2016                    31.90                   49.89   
104   357  2016                    35.87                   52.38   

     Fear of failure rate *  Entrepreneurial intentions  \
291                   44.58                       14.60   
227                   46.51                        2.23   
78    

In [13]:
df = pd.read_csv("project_data.csv")

print(df)

     code         economy  year  Perceived opportunities  \
0     375         Belarus  2021                    25.02   
1     385         Croatia  2021                    58.33   
2     357          Cyprus  2021                    50.17   
3     358         Finland  2021                    61.04   
4      33          France  2021                    52.13   
..    ...             ...   ...                      ...   
455    48          Poland  2001                    13.97   
456   351        Portugal  2001                    22.28   
457    34           Spain  2001                    48.46   
458    46          Sweden  2001                    42.34   
459    44  United Kingdom  2001                    23.00   

     Perceived capabilities  Fear of failure rate *  \
0                     51.96                   56.01   
1                     71.07                   45.58   
2                     64.05                   50.08   
3                     42.75                   44.53   
4   

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("project_data.csv")
cleaned = df
#cleaned = df.drop(['code', 'economy']) # drop unrelated columns
# cleanedAge = cleaned['Age'].fillna(df['Age'].mean()) # fill nulls in Age column with mean age
# cleaned = cleaned.drop(['Age'], axis=1) # drop column with missing values
# cleaned['Age'] = cleanedAge # add cleaned column to dataframe
# cleaned = cleaned.dropna() # drop rows with empty embarked
# from sklearn import preprocessing
# le = preprocessing.LabelEncoder()
# le.fit(cleaned['Embarked'])
# embarked = le.transform(cleaned['Embarked'])
# le.fit(cleaned['Sex'])
# sex = le.transform(cleaned['Sex'])
# cleaned = cleaned.drop(['Embarked', 'Sex'], axis = 1)
# cleaned['Embarked'] = embarked
# cleaned['Sex'] = sex
# cleaned.info()

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import svm
df = pd.read_csv("project_data.csv")
df2 = df.dropna()
y = y.apply(np.int64)
print (y)
clf = svm.SVC()
clf.fit(X_train, y_train)
clf.predict(X_test)
print(y_pred)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


0      13
1      12
2       8
3       7
4       7
       ..
440     4
441     4
442     3
443     7
444     5
Name: Total early-stage Entrepreneurial Activity (TEA), Length: 431, dtype: int64
[ 5  9  2  6  9  4  4  5  5  6  6  7  5  2  3  9  5  9 12  7  6  6  7  5
  5  5  4 14  6  7  5 13  5  5  5 12  8  7  8  5  8  5  6  8  3  3  9  5
  7  7  7  4  7  3  5  6  5  4  5  9  6  7  3  5  9  9  4 11 12  5  8  5
  6  4  8  4  7  5  8  5  5  7  3  5 14  9  7]
[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 2 0 1 0 2 1 0 0 0 0 0 0 0]
 [0 0 2 4 3 2 0 0 0 0 0 0 0 0 0]
 [0 1 1 3 7 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 2 2 1 0 0 1 0 0 0]
 [0 0 0 0 6 3 2 1 2 0 0 0 1 0 0]
 [0 0 0 0 5 0 4 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 2 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 3 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
0.22988505747126436


In [19]:
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()


X = df2[['code', 'year', 'Perceived opportunities', 'Perceived capabilities', 'Fear of failure rate *', 'Entrepreneurial intentions', 'Established Business Ownership', 'Female/Male TEA', 'High Job Creation Expectation', 'Business Services Sector']]
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
X_train = pd.DataFrame(X_train)
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print(y_pred)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[ 4  4  3  5  5  5 10  5  6  8 14  4  7  5  5  9  5  8  9  5  7  5  5  5
 14  5  9 11  9  5 10  7  4 11  5  5 10  4  9  8  4  9 13  5 13  9  4 13
  7  2  7 12  5  4  6  5 10  5  7  4  4  8 13  6  6  9 11  5  4  5  3  8
  4  8  5  6  7  7 12  3  6  5  5  5  3  4 12]
[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 3 2 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 3 3 1 1 0 1 0 0 0 0 0 0]
 [0 1 0 5 8 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 3 2 2 2 2 0 1 1 0 1 0]
 [0 0 0 1 4 1 1 0 1 1 0 1 0 1 0]
 [0 0 0 0 2 0 0 0 3 1 0 0 0 0 0]
 [0 0 0 0 3 0 2 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]
0.19540229885057472
