In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
#loading of the data and selecting most relevant features, dropping columns that are lacking data
df = pd.read_csv("project_data.csv")
df2 = df.dropna()
y = df2['Total early-stage Entrepreneurial Activity (TEA)']

X = df2.drop(['economy','Total early-stage Entrepreneurial Activity (TEA)'], axis=1)

In [2]:
#spliting data, fitting it into Linear Regression 
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
coeff_df = pd.DataFrame(regressor.coef_, X.columns, columns=['Coefficient'])
#printing coefficients
print(coeff_df)


                                Coefficient
code                               0.002311
year                               0.053330
Perceived opportunities            0.020645
Perceived capabilities             0.009280
Fear of failure rate *             0.006511
Entrepreneurial intentions         0.187266
Established Business Ownership     0.236139
Female/Male TEA                    2.177346
High Job Creation Expectation      0.064462
Business Services Sector           0.007680


In [3]:

#making predictions, printing scores
y_pred = regressor.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 1.5213243069253377
Mean Squared Error: 4.402176280247885
Root Mean Squared Error: 2.0981363826615


In [4]:
#predicting using Support vector machine
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import svm
y = y.apply(np.int64)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
clf = svm.SVC()
clf.fit(X_train, y_train)
clf.predict(X_test)
y_pred=pd.DataFrame(y_pred)
y_pred = y_pred.apply(np.int64)
#confusion matrix - important when evaluating how far from the truth was the algorithm 
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[[0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 1 0 0 2 1 1 0 0 0 0 0 0 0]
 [0 0 1 0 2 0 2 0 0 1 0 0 0 0]
 [0 1 1 3 3 2 2 0 1 0 0 1 0 0]
 [1 0 2 0 5 2 3 0 1 1 0 0 0 0]
 [1 1 2 2 5 2 3 0 0 0 0 0 0 0]
 [0 0 1 1 2 2 1 1 1 0 0 0 0 0]
 [0 0 0 1 2 3 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 1 0 0 0 0 0]
 [0 0 0 2 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]]
0.14942528735632185


In [5]:
#prediction using Gaussian NB
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()



X_train = pd.DataFrame(X_train)
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print(y_pred)
#confusion matrix - important when evaluating how far from the truth was the algorithm 
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[ 9  5  7  2 14  3  5  8  5  7  5  5  3  4  5 12 13  6  5  5  9  3  5  5
 13  4  9  9  7  5  9  9  3  7  5  3 13  8  6  5  9  7  3 12  5 13  5  6
  5 13  5  5  5  4  4  5  7  4  3  7  5  8  5  5  9  7  5  5  7  3  2  5
  5  3 10 14  2  9  3  5  5  3 10  6  7  5  3]
[[0 1 0 0 0 0 0 0 0 0 0 0]
 [0 3 0 2 0 1 1 0 0 0 0 0]
 [0 3 1 9 2 0 0 0 0 0 0 0]
 [2 3 1 6 1 2 0 1 0 0 0 0]
 [1 2 2 4 0 3 0 2 0 0 1 0]
 [0 0 0 4 0 1 0 2 0 0 1 1]
 [0 0 1 3 1 1 0 1 1 0 1 0]
 [0 0 0 2 0 1 1 2 1 0 1 0]
 [0 0 0 0 0 1 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1]]
0.16091954022988506
